### ISSUE TITLE
Установить Youtube на базе youtube-local

### ISSUE THREAD

**Issue by FanattLeshenko1** [IlKorotkiy/NDRRunet#2]
Установить на сервер youtube из репозитория по ссылке https://github.com/user234683/youtube-local

**Comment by Endedman** [comment]
user clipbucket

**Comment by LauncherM** [comment]
Пиши подробнее, надо что бы все понимали что ты имеешь ввиду

**Comment by Endedman** [comment]
clipbucket - инстанция ютуба для старых пк. Указывается в issue, этот же закрываю
