### ISSUE TITLE
Добавить flash player

### ISSUE THREAD

**Issue by LauncherM** [IlKorotkiy/NDRRunet#4]
Прикрутить флеш плеер, так как ориентировано на старые пк.

**Comment by Endedman** [comment]
Неправильная формулировка. Сделать выбор между Флеш и JS плеером

**Comment by LauncherM** [comment]
Для этого наверно надо для начала добавить flash player? Или там из коробки он?

**Comment by Endedman** [comment]
из коробки должен быть

**Comment by FanattLeshenko1** [comment]
Так

**Comment by Endedman** [comment]
Закрыто, используем clipbucket player. Вы можете в любой момент открыть issue, если что то пошло не так
