### ISSUE TITLE
Определиться с минимальными требованиями для сайта

### ISSUE THREAD

**Issue by LauncherM** [IlKorotkiy/NDRRunet#8]
Разобраться какие минимальные версии браузеров должен поддерживать сайт. И добавить эту инфу на страничку http://narodweb.ru/dev/

**Comment by nnsby** [comment]
Опера 11 - ?

**Comment by Endedman** [comment]
Мннимальными требованиями могу определить:
IE4 - Windows 95
Arachne - DOS
Mozilla compatible - 9
Opera compatible - 11
Хромоподобные - 4

**Comment by LauncherM** [comment]
Огромный разрыв: Arachne и опера 11
 Нам точно надо ие4, это прям совсем слабо?
Опере 11 по датам выпуска соответствует ие8

**Comment by FanattLeshenko1** [comment]
Opera Mini - 7
Стандартный браузер Symbian 9.4 (версии не посмотреть)

**Comment by nnsby** [comment]
Сайт должен корректно отображаться и полноценно функционировать на Опера 11 (ИЕ 8) и выше. 
Отображение и функционирование сайта в браузерах Арахна, ИЕ4 и т.п. можно пренебречь.

**Comment by LauncherM** [comment]
Было решено поддерживать минимальные версии браузеров:

- Opera 11 (https://en.wikipedia.org/wiki/History_of_the_Opera_web_browser#Version_11)
- Firefox 3.6.x (https://website-archive.mozilla.org/www.mozilla.org/firefox_releasenotes/en-us/firefox/3.6/releasenotes/)
- IE 8 (https://en.wikipedia.org/wiki/Internet_Explorer_8)
- Chrome 8 (https://chromereleases.googleblog.com/2010/12/)

**Comment by LauncherM** [comment]
@Endedman добавь список версий на сайт пожалуйста
